---
title: "p8105_hw2_hz3023"
author: "Huiyi Zhu"
date: "2025-10-01"
output: github_document
---
##Question 1
```{r Question1, Part 1}
library(tidyverse)
pols_df=
  read_csv(file = "/Users/huiyizhu/Desktop/Columbia/Fall 2025/Data Science I/fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into=c("year","month","day"), sep="-") |> 
  pivot_longer(
    cols=c(prez_gop,prez_dem),
    names_to = "president",
    values_to = "value",
    names_prefix = "prez_"
  ) |> 
   mutate(
     month= match(month, month.abb),
     year= as.integer(year))|> 
  select(year, month, gov_gop, sen_gop, rep_gop,gov_dem, rep_dem, president )
```

```{r Question1, Part 2}
snp_df =
  read_csv(file = "/Users/huiyizhu/Desktop/Columbia/Fall 2025/Data Science I/fivethirtyeight_datasets/snp.csv")|> 
  janitor::clean_names() |> 
  separate(date, into = c("month","day","year"), sep = "/") |> 
  mutate(
     year  = if_else(as.integer(year) > 20, 
                  1900 + as.integer(year), 
                  2000 + as.integer(year)
          ),
    month = as.integer(month)
  ) |> 
  select(year, month, close)
```

```{r Question1, Part 3}
unemployment_df =
 read_csv(file = "/Users/huiyizhu/Desktop/Columbia/Fall 2025/Data Science I/fivethirtyeight_datasets/unemployment.csv") |>
  pivot_longer(
    cols =(Jan:Dec),
    names_to  = "month",
    values_to = "unemployment"
  ) |>
mutate(
     month= match(month, month.abb),
     year= as.integer(Year))|> 
  select(year, month, unemployment)
```

```{r}
merged_df = 
  left_join(pols_df, snp_df, by = c("year", "month")) |>
  left_join(unemployment_df, by = c("year", "month"))
```

